version: '3.8'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - .:/single-player-tic-tac-toe
    php:
        image: php:fpm
        volumes:
            - .:/single-player-tic-tac-toe